-- CreateTable
CREATE TABLE "Post" (
    "ID" TEXT NOT NULL PRIMARY KEY,
    "CREATED_AT" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "OWNER_ID" TEXT NOT NULL,
    "CONTENT" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "User" (
    "ID" TEXT NOT NULL PRIMARY KEY,
    "CREATED_AT" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "POSTS_ID" TEXT NOT NULL DEFAULT '',
    "ROLES" TEXT NOT NULL DEFAULT 'READ/WRITE',
    "USERNAME" TEXT NOT NULL,
    "PASSWORD_HASH" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "Session" (
    "ID" TEXT NOT NULL PRIMARY KEY,
    "CREATED_AT" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "TOKEN" TEXT NOT NULL,
    "USER_ID" TEXT NOT NULL
);

-- CreateIndex
CREATE UNIQUE INDEX "User_USERNAME_key" ON "User"("USERNAME");

-- CreateIndex
CREATE UNIQUE INDEX "Session_USER_ID_key" ON "Session"("USER_ID");
