-- CreateTable
CREATE TABLE "Post" (
    "ID" TEXT NOT NULL,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "OWNER_ID" TEXT NOT NULL,
    "CONTENT" TEXT NOT NULL,

    CONSTRAINT "Post_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "User" (
    "ID" TEXT NOT NULL,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "POSTS_ID" TEXT NOT NULL DEFAULT '',
    "ROLES" TEXT NOT NULL DEFAULT 'READ/WRITE',
    "USERNAME" TEXT NOT NULL,
    "PASSWORD_HASH" TEXT NOT NULL,

    CONSTRAINT "User_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "Session" (
    "ID" TEXT NOT NULL,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "TOKEN" TEXT NOT NULL,
    "USER_ID" TEXT NOT NULL,

    CONSTRAINT "Session_pkey" PRIMARY KEY ("ID")
);

-- CreateIndex
CREATE UNIQUE INDEX "User_USERNAME_key" ON "User"("USERNAME");

-- CreateIndex
CREATE UNIQUE INDEX "Session_USER_ID_key" ON "Session"("USER_ID");
